{{- if .Values.mongoSvc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongoSvc.name }}
spec:
  selector:
    app: {{ .Values.mongoSvc.name }}
  ports:
    - port: {{ .Values.mongoSvc.port }}
      targetPort: {{ .Values.mongo.containerPort }}
{{- end }}