{{- if .Values.clientSvc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clientSvc.name }}
spec:
  selector:
    app: {{ .Values.client.name }}
  ports:
    - port: {{ .Values.clientSvc.port }}
      protocol: {{ .Values.clientSvc.protocol }}
      targetPort: {{ .Values.client.containerPort }}
  type: {{ .Values.clientSvc.type }}
{{- end }}